---
title: "clustering-code-R"
---

# Libraries

```{r}
library(tidymodels)
library(tidyverse)
library(tidyclust)
library(rio)


```

# Importacion y tratamiento de la data

```{r}
data <- import("marketing_campaign.csv")
```

```{r}
str(data)
```

## Buscamos valores faltantes y duplicados

```{r}
na_dup <- function(data) {
  missing_values <- colSums(is.na(data))
  missing_values_perc <- missing_values / nrow(data) * 100
  duplicated_values <- sum(duplicated(data))
  duplicated_values_perc <- duplicated_values / nrow(data) * 100
  data_types <- sapply(data, class)
  
  resumen <- data.frame(
    Valores_Faltantes  = missing_values,
    Valores_Faltantes_Porcentaje = missing_values_perc,
    Valores_Duplicados = duplicated_values,
    Valores_Duplicados_Porcentaje = duplicated_values_perc,
    Tipo_de_Variable = data_types,
    stringsAsFactors = FALSE
  )
  
  return(resumen)
}

na_dup(data)
```

- Se identificó que la columna **Income** tiene valores faltantes, por lo cual se procesera a la imputacion de los datos
- No se identificaron valores duplicados

```{r}
data <- data |>
        mutate(Income = replace(Income, is.na(Income), mean(Income, na.rm = TRUE)))

```

Verificamos que no haya datos faltantes
```{r}
na_dup(data)
```



